name: Release
# on:
#   push:
#     branches:
#       - master
on:
  repository_dispatch:
    types: [semantic-release]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git User
        run: |
          git config --local user.email 'dan.ctions.user@users.noreply.github.com'
          git config --local user.name 'DAN Action User'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout master
        run: git checkout master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@dan-akl'

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: npm run lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
